// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token-bucket.proto

package tokenbucket

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateBucketRequest struct {
	RefillTime           int64    `protobuf:"varint,1,opt,name=refillTime,proto3" json:"refillTime,omitempty"`
	MaxAmount            int64    `protobuf:"varint,2,opt,name=maxAmount,proto3" json:"maxAmount,omitempty"`
	RefillAmount         int64    `protobuf:"varint,3,opt,name=refillAmount,proto3" json:"refillAmount,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketRequest) Reset()         { *m = CreateBucketRequest{} }
func (m *CreateBucketRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBucketRequest) ProtoMessage()    {}
func (*CreateBucketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{1}
}

func (m *CreateBucketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketRequest.Unmarshal(m, b)
}
func (m *CreateBucketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketRequest.Marshal(b, m, deterministic)
}
func (m *CreateBucketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketRequest.Merge(m, src)
}
func (m *CreateBucketRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBucketRequest.Size(m)
}
func (m *CreateBucketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketRequest proto.InternalMessageInfo

func (m *CreateBucketRequest) GetRefillTime() int64 {
	if m != nil {
		return m.RefillTime
	}
	return 0
}

func (m *CreateBucketRequest) GetMaxAmount() int64 {
	if m != nil {
		return m.MaxAmount
	}
	return 0
}

func (m *CreateBucketRequest) GetRefillAmount() int64 {
	if m != nil {
		return m.RefillAmount
	}
	return 0
}

func (m *CreateBucketRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateBucketResponse struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBucketResponse) Reset()         { *m = CreateBucketResponse{} }
func (m *CreateBucketResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBucketResponse) ProtoMessage()    {}
func (*CreateBucketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{2}
}

func (m *CreateBucketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBucketResponse.Unmarshal(m, b)
}
func (m *CreateBucketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBucketResponse.Marshal(b, m, deterministic)
}
func (m *CreateBucketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBucketResponse.Merge(m, src)
}
func (m *CreateBucketResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBucketResponse.Size(m)
}
func (m *CreateBucketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBucketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBucketResponse proto.InternalMessageInfo

func (m *CreateBucketResponse) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type AddTokenRequest struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTokenRequest) Reset()         { *m = AddTokenRequest{} }
func (m *AddTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AddTokenRequest) ProtoMessage()    {}
func (*AddTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{3}
}

func (m *AddTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTokenRequest.Unmarshal(m, b)
}
func (m *AddTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTokenRequest.Marshal(b, m, deterministic)
}
func (m *AddTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTokenRequest.Merge(m, src)
}
func (m *AddTokenRequest) XXX_Size() int {
	return xxx_messageInfo_AddTokenRequest.Size(m)
}
func (m *AddTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTokenRequest proto.InternalMessageInfo

func (m *AddTokenRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type ConsumeTokenRequest struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeTokenRequest) Reset()         { *m = ConsumeTokenRequest{} }
func (m *ConsumeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeTokenRequest) ProtoMessage()    {}
func (*ConsumeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{4}
}

func (m *ConsumeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeTokenRequest.Unmarshal(m, b)
}
func (m *ConsumeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeTokenRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeTokenRequest.Merge(m, src)
}
func (m *ConsumeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeTokenRequest.Size(m)
}
func (m *ConsumeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeTokenRequest proto.InternalMessageInfo

func (m *ConsumeTokenRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type ConsumeTokenResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeTokenResponse) Reset()         { *m = ConsumeTokenResponse{} }
func (m *ConsumeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumeTokenResponse) ProtoMessage()    {}
func (*ConsumeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{5}
}

func (m *ConsumeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeTokenResponse.Unmarshal(m, b)
}
func (m *ConsumeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeTokenResponse.Marshal(b, m, deterministic)
}
func (m *ConsumeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeTokenResponse.Merge(m, src)
}
func (m *ConsumeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumeTokenResponse.Size(m)
}
func (m *ConsumeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeTokenResponse proto.InternalMessageInfo

func (m *ConsumeTokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type RefillTokenRequest struct {
	BucketName           string   `protobuf:"bytes,1,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefillTokenRequest) Reset()         { *m = RefillTokenRequest{} }
func (m *RefillTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefillTokenRequest) ProtoMessage()    {}
func (*RefillTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{6}
}

func (m *RefillTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefillTokenRequest.Unmarshal(m, b)
}
func (m *RefillTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefillTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefillTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefillTokenRequest.Merge(m, src)
}
func (m *RefillTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefillTokenRequest.Size(m)
}
func (m *RefillTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefillTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefillTokenRequest proto.InternalMessageInfo

func (m *RefillTokenRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

type RefillTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefillTokenResponse) Reset()         { *m = RefillTokenResponse{} }
func (m *RefillTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefillTokenResponse) ProtoMessage()    {}
func (*RefillTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{7}
}

func (m *RefillTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefillTokenResponse.Unmarshal(m, b)
}
func (m *RefillTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefillTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefillTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefillTokenResponse.Merge(m, src)
}
func (m *RefillTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefillTokenResponse.Size(m)
}
func (m *RefillTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefillTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefillTokenResponse proto.InternalMessageInfo

type AddTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTokenResponse) Reset()         { *m = AddTokenResponse{} }
func (m *AddTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AddTokenResponse) ProtoMessage()    {}
func (*AddTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e621357f752d376e, []int{8}
}

func (m *AddTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTokenResponse.Unmarshal(m, b)
}
func (m *AddTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTokenResponse.Marshal(b, m, deterministic)
}
func (m *AddTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTokenResponse.Merge(m, src)
}
func (m *AddTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AddTokenResponse.Size(m)
}
func (m *AddTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTokenResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Token)(nil), "tokenbucket.Token")
	proto.RegisterType((*CreateBucketRequest)(nil), "tokenbucket.CreateBucketRequest")
	proto.RegisterType((*CreateBucketResponse)(nil), "tokenbucket.CreateBucketResponse")
	proto.RegisterType((*AddTokenRequest)(nil), "tokenbucket.AddTokenRequest")
	proto.RegisterType((*ConsumeTokenRequest)(nil), "tokenbucket.ConsumeTokenRequest")
	proto.RegisterType((*ConsumeTokenResponse)(nil), "tokenbucket.ConsumeTokenResponse")
	proto.RegisterType((*RefillTokenRequest)(nil), "tokenbucket.RefillTokenRequest")
	proto.RegisterType((*RefillTokenResponse)(nil), "tokenbucket.RefillTokenResponse")
	proto.RegisterType((*AddTokenResponse)(nil), "tokenbucket.AddTokenResponse")
}

func init() { proto.RegisterFile("token-bucket.proto", fileDescriptor_e621357f752d376e) }

var fileDescriptor_e621357f752d376e = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0xc7, 0x0b, 0xfd, 0x88, 0x9d, 0x36, 0x6a, 0x86, 0x1a, 0x09, 0xa9, 0x8a, 0x7b, 0xe2, 0x22,
	0x89, 0xf5, 0xe3, 0x6c, 0xed, 0xc9, 0x83, 0x1e, 0x48, 0x7d, 0x00, 0x2a, 0x6b, 0x42, 0x5a, 0xd8,
	0x0a, 0x4b, 0xe2, 0x3b, 0xf8, 0x7c, 0xbe, 0x8f, 0x61, 0x97, 0xda, 0x5d, 0xfa, 0x91, 0xf4, 0x06,
	0x7f, 0x7e, 0x33, 0xf3, 0x9f, 0xff, 0x04, 0x40, 0xce, 0xe6, 0x34, 0xbd, 0x99, 0x15, 0x1f, 0x73,
	0xca, 0xfd, 0x65, 0xc6, 0x38, 0xc3, 0x9e, 0xd0, 0xa4, 0x44, 0xce, 0xa1, 0x3d, 0x2d, 0x5f, 0xf1,
	0x18, 0xcc, 0x38, 0xb2, 0x4d, 0xd7, 0xf0, 0x9a, 0x81, 0x19, 0x47, 0xe4, 0xc7, 0x00, 0x6b, 0x92,
	0xd1, 0x90, 0xd3, 0x67, 0x41, 0x06, 0xf4, 0xab, 0xa0, 0x39, 0xc7, 0x4b, 0x80, 0x8c, 0x7e, 0xc6,
	0x8b, 0xc5, 0x34, 0x4e, 0xa8, 0x6d, 0x08, 0x5e, 0x51, 0x70, 0x08, 0xdd, 0x24, 0xfc, 0x1e, 0x27,
	0xac, 0x48, 0x79, 0xd5, 0x6e, 0x2d, 0x20, 0x81, 0xbe, 0x64, 0x2b, 0xa0, 0x29, 0x00, 0x4d, 0x43,
	0x84, 0x56, 0x1a, 0x26, 0xd4, 0x6e, 0xb9, 0x86, 0xd7, 0x0d, 0xc4, 0x33, 0x79, 0x84, 0x81, 0x6e,
	0x26, 0x5f, 0xb2, 0x34, 0xa7, 0xa5, 0x1b, 0xb9, 0xc8, 0x5b, 0x58, 0xb9, 0xe9, 0x06, 0x8a, 0x42,
	0x6e, 0xe1, 0x64, 0x1c, 0x45, 0x62, 0x43, 0x65, 0x81, 0xbd, 0x25, 0x0f, 0x60, 0x4d, 0x58, 0x9a,
	0x17, 0x09, 0x3d, 0xa8, 0xec, 0x09, 0x06, 0x7a, 0x59, 0xe5, 0xd0, 0x83, 0xb6, 0xc8, 0x5b, 0x94,
	0xf4, 0x46, 0xe8, 0x2b, 0xe9, 0xfb, 0x12, 0x95, 0x00, 0xb9, 0x07, 0x0c, 0x64, 0x8e, 0x87, 0xcc,
	0x3d, 0x03, 0x4b, 0xab, 0x92, 0x63, 0x09, 0xc2, 0xe9, 0x7a, 0x71, 0xa9, 0x8d, 0x7e, 0x4d, 0xe8,
	0x09, 0x45, 0x86, 0x88, 0xef, 0xd0, 0x57, 0x43, 0x45, 0x57, 0xf3, 0xb6, 0xe5, 0xf8, 0xce, 0xf5,
	0x1e, 0xa2, 0x1a, 0xdc, 0xc0, 0x17, 0x38, 0x5a, 0x8d, 0xc6, 0xa1, 0x56, 0x50, 0x3b, 0x85, 0x73,
	0xb1, 0xe3, 0xeb, 0x7f, 0xab, 0xd2, 0xa1, 0x12, 0x6a, 0xdd, 0xe1, 0xe6, 0x99, 0xea, 0x0e, 0xb7,
	0x5c, 0x84, 0x34, 0xf0, 0x15, 0x3a, 0x32, 0x33, 0xbc, 0xd2, 0xf0, 0xcd, 0xf8, 0x1d, 0x77, 0x37,
	0xb0, 0x6a, 0x37, 0xeb, 0x88, 0xff, 0xea, 0xee, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x11, 0x91, 0x61,
	0x8f, 0x6d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenBucketClient is the client API for TokenBucket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenBucketClient interface {
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	AddToken(ctx context.Context, in *AddTokenRequest, opts ...grpc.CallOption) (*AddTokenResponse, error)
	ConsumeToken(ctx context.Context, in *ConsumeTokenRequest, opts ...grpc.CallOption) (*ConsumeTokenResponse, error)
	Refill(ctx context.Context, in *RefillTokenRequest, opts ...grpc.CallOption) (*RefillTokenResponse, error)
}

type tokenBucketClient struct {
	cc *grpc.ClientConn
}

func NewTokenBucketClient(cc *grpc.ClientConn) TokenBucketClient {
	return &tokenBucketClient{cc}
}

func (c *tokenBucketClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, "/tokenbucket.TokenBucket/CreateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenBucketClient) AddToken(ctx context.Context, in *AddTokenRequest, opts ...grpc.CallOption) (*AddTokenResponse, error) {
	out := new(AddTokenResponse)
	err := c.cc.Invoke(ctx, "/tokenbucket.TokenBucket/AddToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenBucketClient) ConsumeToken(ctx context.Context, in *ConsumeTokenRequest, opts ...grpc.CallOption) (*ConsumeTokenResponse, error) {
	out := new(ConsumeTokenResponse)
	err := c.cc.Invoke(ctx, "/tokenbucket.TokenBucket/ConsumeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenBucketClient) Refill(ctx context.Context, in *RefillTokenRequest, opts ...grpc.CallOption) (*RefillTokenResponse, error) {
	out := new(RefillTokenResponse)
	err := c.cc.Invoke(ctx, "/tokenbucket.TokenBucket/Refill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenBucketServer is the server API for TokenBucket service.
type TokenBucketServer interface {
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	AddToken(context.Context, *AddTokenRequest) (*AddTokenResponse, error)
	ConsumeToken(context.Context, *ConsumeTokenRequest) (*ConsumeTokenResponse, error)
	Refill(context.Context, *RefillTokenRequest) (*RefillTokenResponse, error)
}

// UnimplementedTokenBucketServer can be embedded to have forward compatible implementations.
type UnimplementedTokenBucketServer struct {
}

func (*UnimplementedTokenBucketServer) CreateBucket(ctx context.Context, req *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (*UnimplementedTokenBucketServer) AddToken(ctx context.Context, req *AddTokenRequest) (*AddTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToken not implemented")
}
func (*UnimplementedTokenBucketServer) ConsumeToken(ctx context.Context, req *ConsumeTokenRequest) (*ConsumeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumeToken not implemented")
}
func (*UnimplementedTokenBucketServer) Refill(ctx context.Context, req *RefillTokenRequest) (*RefillTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refill not implemented")
}

func RegisterTokenBucketServer(s *grpc.Server, srv TokenBucketServer) {
	s.RegisterService(&_TokenBucket_serviceDesc, srv)
}

func _TokenBucket_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenBucketServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenbucket.TokenBucket/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenBucketServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenBucket_AddToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenBucketServer).AddToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenbucket.TokenBucket/AddToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenBucketServer).AddToken(ctx, req.(*AddTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenBucket_ConsumeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenBucketServer).ConsumeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenbucket.TokenBucket/ConsumeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenBucketServer).ConsumeToken(ctx, req.(*ConsumeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenBucket_Refill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefillTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenBucketServer).Refill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenbucket.TokenBucket/Refill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenBucketServer).Refill(ctx, req.(*RefillTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenBucket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenbucket.TokenBucket",
	HandlerType: (*TokenBucketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _TokenBucket_CreateBucket_Handler,
		},
		{
			MethodName: "AddToken",
			Handler:    _TokenBucket_AddToken_Handler,
		},
		{
			MethodName: "ConsumeToken",
			Handler:    _TokenBucket_ConsumeToken_Handler,
		},
		{
			MethodName: "Refill",
			Handler:    _TokenBucket_Refill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token-bucket.proto",
}
